# Labels for tracking statistics and history
- name: Enhancement
  color: f5f7f9
  description: "A general update to the code base."
- name: Bug
  color: f5f7f9
  description: "An update to fix incorrect code or typos."

# Labels to visually distinguish special types of issues
- name: Urgent
  color: "00FFFF"
  description: "Very important and needs attention"
- name: Epic
  color: "d8bfd8"
  description: "Contains many smaller pieces to work on separately"
- name: Internal
  color: "f2bb22"
  description: "To help track internal tickets in a single location."
