name: "Validate AWS Doc SDK Examples Metadata"
description: "A GitHub Action that validates metadata for projects that expose snippets via AWS Doc SDK Examples"
inputs:
  root:
    description: "Root of the repository checkout to validate metadata within"
    default: ${{ github.workspace }}
  doc_gen_only:
    description: "Only perform extended validation on doc_gen snippets"
    default: "True"
  strict_titles:
    description: "Strict mode for titles: disallow title/title_abbrev/sysnopsis for Action examples, require otherwise."
    default: "False"
runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install Dependencies
      run: pip install -e "${{ github.action_path }}"
      shell: bash
    - name: Run validator
      run: python3 -m "aws_doc_sdk_examples_tools.validate" --root "${{ inputs.root }}" --doc_gen_only "${{ inputs.doc_gen_only }}" --strict_titles "${{ inputs.strict_titles }}"
      shell: bash
