name: Label Checker
on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check_stats_labels:
    name: Check Stats labels
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          one_of: Enhancement,Bug
          repo_token: ${{ secrets.GITHUB_TOKEN }}
